---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - subscription.yaml
  - https://raw.githubusercontent.com/rohit-taneja-redhat/gitops-catalog/refs/heads/main/grafana-operator/base/operator/kustomization.yaml
